-- Gerado por scripts/gen_tiles.py: não edite à mão (rode o script de novo).
-- Texturas próprias do Outro Mundo estilo Silent Hill (sprint 0035). O nome do sprite é o
-- caminho do PNG, o mesmo do getTexture (spike-sprite-proprio.md §1b). Lado F = chão
-- (FloorOverlay); W e N = parede oeste e norte (WallOverlay + attachedW ou attachedN).
NOM_OwnSpriteList = {
    DIR = "media/textures/NOM/OutroMundo/",
    SPRITES = {
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Grade_F_01.png", side = "F", kind = "Grade" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Grade_F_02.png", side = "F", kind = "Grade" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Grade_F_03.png", side = "F", kind = "Grade" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Grade_F_04.png", side = "F", kind = "Grade" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Grade_F_05.png", side = "F", kind = "Grade" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_F_01.png", side = "F", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_F_02.png", side = "F", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_F_03.png", side = "F", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_F_04.png", side = "F", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_F_05.png", side = "F", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Chapa_F_01.png", side = "F", kind = "Chapa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Chapa_F_02.png", side = "F", kind = "Chapa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Chapa_F_03.png", side = "F", kind = "Chapa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Chapa_F_04.png", side = "F", kind = "Chapa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Chapa_F_05.png", side = "F", kind = "Chapa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_F_01.png", side = "F", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_F_02.png", side = "F", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_F_03.png", side = "F", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_F_04.png", side = "F", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_F_05.png", side = "F", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_W_01.png", side = "W", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_W_02.png", side = "W", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_W_03.png", side = "W", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_W_04.png", side = "W", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_W_05.png", side = "W", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_W_01.png", side = "W", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_W_02.png", side = "W", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_W_03.png", side = "W", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_W_04.png", side = "W", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_W_05.png", side = "W", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_W_01.png", side = "W", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_W_02.png", side = "W", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_W_03.png", side = "W", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_W_04.png", side = "W", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_W_05.png", side = "W", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_N_01.png", side = "N", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_N_02.png", side = "N", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_N_03.png", side = "N", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_N_04.png", side = "N", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Tinta_N_05.png", side = "N", kind = "Tinta" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_N_01.png", side = "N", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_N_02.png", side = "N", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_N_03.png", side = "N", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_N_04.png", side = "N", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Ferrugem_N_05.png", side = "N", kind = "Ferrugem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_N_01.png", side = "N", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_N_02.png", side = "N", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_N_03.png", side = "N", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_N_04.png", side = "N", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Descasca_N_05.png", side = "N", kind = "Descasca" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Cinza_F_01.png", side = "F", kind = "Cinza" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Cinza_F_02.png", side = "F", kind = "Cinza" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Cinza_F_03.png", side = "F", kind = "Cinza" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Cinza_F_04.png", side = "F", kind = "Cinza" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Cinza_F_05.png", side = "F", kind = "Cinza" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Brasa_F_01.png", side = "F", kind = "Brasa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Brasa_F_02.png", side = "F", kind = "Brasa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Brasa_F_03.png", side = "F", kind = "Brasa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Brasa_F_04.png", side = "F", kind = "Brasa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Brasa_F_05.png", side = "F", kind = "Brasa" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_W_01.png", side = "W", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_W_02.png", side = "W", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_W_03.png", side = "W", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_W_04.png", side = "W", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_W_05.png", side = "W", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_N_01.png", side = "N", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_N_02.png", side = "N", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_N_03.png", side = "N", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_N_04.png", side = "N", kind = "Fuligem" },
        { name = "media/textures/NOM/OutroMundo/NOM_OM_Fuligem_N_05.png", side = "N", kind = "Fuligem" },
    },
}

return NOM_OwnSpriteList
