require "NOM_DebugRules"

local D = NOM_DebugRules

return {
    debug_rules_parse_accepts_known_ops = function()
        local a = D.parse({ op = "night", value = true })
        assert(a.op == "night" and a.value == true)
        a = D.parse({ op = "night" })
        assert(a.op == "night" and a.value == nil, "nil devolve pro clima")
        -- névoa é evento (sprint 0009): true começa (skip pula a espera da sirene), false/nil termina
        a = D.parse({ op = "fog", value = true, skip = true })
        assert(a.value == true and a.skip == true)
        a = D.parse({ op = "fog", value = true })
        assert(a.value == true and a.skip == false)
        assert(D.parse({ op = "fog" }).value == false, "nil termina")
        assert(D.parse({ op = "fog", value = false }).value == false)
        a = D.parse({ op = "variant", id = -2147000000, kind = "estalador" })
        assert(a.id == -2147000000 and a.kind == "estalador")
        assert(D.parse({ op = "variant", id = 5 }).kind == nil, "kind nil limpa")
        assert(D.parse({ op = "spawnEco" }).op == "spawnEco")
        assert(D.parse({ op = "status" }).op == "status")
        assert(D.parse({ op = "alma" }).op == "alma")
        local ar = D.parse({ op = "arrasto", id = 12 })
        assert(ar and ar.op == "arrasto" and ar.id == 12 and ar.skip == false)
        assert(D.parse({ op = "arrasto", id = -1, skip = true }).skip == true)
        assert(D.parse({ op = "arrasto" }) == nil)
        assert(D.parse({ op = "arrasto", id = "x" }) == nil)
        assert(D.parse({ op = "wander" }).op == "wander")
        assert(D.parse({ op = "sonar" }).op == "sonar")
        assert(D.parse({ op = "thunder" }).op == "thunder")
        assert(D.parse({ op = "lampFlicker" }).op == "lampFlicker")
        assert(D.parse({ op = "rain" }).op == "rain")
        local b = D.parse({ op = "sonarBurst", mode = "B" })
        assert(b.op == "sonarBurst" and b.mode == "B")
        assert(D.parse({ op = "sonarBurst" }).mode == nil)
        assert(D.parse({ op = "sonarBurst", mode = 2 }).mode == 2)
        local g = D.parse({ op = "sonarGaps", delta = 50 })
        assert(g.op == "sonarGaps" and g.delta == 50 and g.reset == false)
        assert(D.parse({ op = "sonarGaps", reset = true }).reset == true)
        assert(D.parse({ op = "sonarGaps", delta = 0 }) == nil)
        assert(D.parse({ op = "sonarGaps" }) == nil)
    end,
    debug_rules_parse_rejects_garbage = function()
        assert(D.parse(nil) == nil)
        assert(D.parse({ op = "kill" }) == nil)
        assert(D.parse({ op = "night", value = "sim" }) == nil)
        assert(D.parse({ op = "fog", value = "muito" }) == nil)
        assert(D.parse({ op = "fog", value = 0.8 }) == nil, "intensidade não existe mais")
        assert(D.parse({ op = "fog", value = true, skip = "sim" }) == nil)
        assert(D.parse({ op = "variant", id = 0, kind = "corredor" }) == nil, "ID 0 é zumbi sem outfit")
        assert(D.parse({ op = "variant", kind = "corredor" }) == nil)
        assert(D.parse({ op = "variant", id = 5, kind = "carrasco" }) == nil)
        assert(D.parse({ op = "variant", id = 5, kind = "carpideira" }).kind == "carpideira", "Carpideira (0011) recusada")
    end,
    debug_rules_line_is_sorted = function()
        assert(D.line("[NOM] x", { b = 2, a = true, c = "z" }) == "[NOM] x a=true b=2 c=z")
        assert(D.line("[NOM] x", {}) == "[NOM] x")
    end,
    -- NaN não é igual a si mesmo: viraria uma chave que ninguém acha (variante) ou
    -- passaria pelo math.max/min sem ser preso (névoa)
    debug_rules_parse_rejects_nan = function()
        local nan = 0 / 0
        assert(D.parse({ op = "variant", id = nan, kind = "corredor" }) == nil)
    end,
    -- névoa vermelha (sprint 0010): true força, false/nil desfaz; só booleano
    debug_rules_parse_red_fog = function()
        assert(D.parse({ op = "redFog", value = true }).value == true)
        assert(D.parse({ op = "redFog", value = false }).value == false)
        assert(D.parse({ op = "redFog" }).value == false)
        assert(D.parse({ op = "redFog", value = "sim" }) == nil)
        assert(D.parse({ op = "redFog", value = 1 }) == nil)
        -- sprint 0020: toggle decidido no servidor
        assert(D.parse({ op = "redFog", toggle = true }).toggle == true)
        assert(D.parse({ op = "redFog", value = true }).toggle == false)
        assert(D.parse({ op = "redFog", toggle = 1 }) == nil)
    end,
    -- sprint 0020: hora do relógio (NOM.time), 0 ≤ h < 24
    debug_rules_parse_time = function()
        assert(D.parse({ op = "time", hour = 0 }).hour == 0)
        assert(D.parse({ op = "time", hour = 23.5 }).hour == 23.5)
        assert(D.parse({ op = "time", hour = 24 }) == nil)
        assert(D.parse({ op = "time", hour = -1 }) == nil)
        assert(D.parse({ op = "time", hour = 0 / 0 }) == nil)
        assert(D.parse({ op = "time", hour = "12" }) == nil)
        assert(D.parse({ op = "time" }) == nil)
    end,
    -- spawn: 1..50 inteiro; o resto não passa
    debug_rules_spawn_clamps = function()
        assert(D.MAX_SPAWN == 50)
        assert(D.clampSpawn(1000) == 50)
        assert(D.clampSpawn(-3) == 1)
        assert(D.clampSpawn(0) == 1)
        assert(D.clampSpawn(2.7) == 2)
        assert(D.clampSpawn(10) == 10)
        assert(D.clampSpawn(0 / 0) == nil)
        assert(D.clampSpawn(1 / 0) == 50)
        assert(D.clampSpawn("x") == nil)
        assert(D.clampSpawn(nil) == nil)
    end,
    debug_rules_parse_spawn = function()
        local a = D.parse({ op = "spawn", n = 500, outfit = "Police", x = 10.5, y = 20.5, z = 0 })
        assert(a.n == 50 and a.outfit == "Police" and a.x == 10.5 and a.y == 20.5 and a.z == 0)
        assert(D.parse({ op = "spawn", n = 1, x = 1, y = 1, z = 0 }).outfit == nil, "outfit nil = sorteado")
        assert(D.parse({ op = "spawn", n = 1, outfit = 5, x = 1, y = 1, z = 0 }) == nil)
        assert(D.parse({ op = "spawn", n = 1, outfit = string.rep("a", 65), x = 1, y = 1, z = 0 }) == nil)
        assert(D.parse({ op = "spawn", n = 1, x = 1, y = 0 / 0, z = 0 }) == nil)
        assert(D.parse({ op = "spawn", n = 1, x = 1, y = 1 }) == nil)
        assert(D.parse({ op = "spawn", n = "x", x = 1, y = 1, z = 0 }) == nil)
    end,
    -- sprint 0033: puxar o zumbi mais perto (NOM.getZombie); id -1 = sem ID de rede (solo)
    debug_rules_parse_pull = function()
        local a = D.parse({ op = "pull", id = 12, x = 100, y = 200, z = 1 })
        assert(a.op == "pull" and a.id == 12 and a.x == 100 and a.y == 200 and a.z == 1)
        assert(D.parse({ op = "pull", id = -1, x = 1, y = 1, z = 0 }).id == -1, "solo manda -1")
        assert(D.parse({ op = "pull", x = 1, y = 1, z = 0 }) == nil)
        assert(D.parse({ op = "pull", id = "a", x = 1, y = 1, z = 0 }) == nil)
        assert(D.parse({ op = "pull", id = 0 / 0, x = 1, y = 1, z = 0 }) == nil)
        assert(D.parse({ op = "pull", id = 1, x = 0 / 0, y = 1, z = 0 }) == nil)
        assert(D.parse({ op = "pull", id = 1, x = 1, y = 1 / 0, z = 0 }) == nil)
        assert(D.parse({ op = "pull", id = 1, x = 1, y = 1 }) == nil)
    end,
    -- sprint 0033: névoa na cor pedida (NOM.setFog / NOM.setRedFog)
    debug_rules_parse_set_fog = function()
        local a = D.parse({ op = "setFog", red = true, skip = true })
        assert(a.op == "setFog" and a.red == true and a.skip == true)
        a = D.parse({ op = "setFog", red = false })
        assert(a.red == false and a.skip == false, "skip nil é falso")
        assert(D.parse({ op = "setFog" }).red == false, "red nil é branca")
        assert(D.parse({ op = "setFog", red = "sim" }) == nil)
        assert(D.parse({ op = "setFog", red = true, skip = 1 }) == nil)
    end,
    -- toggle da névoa: quem decide é o servidor (sabe da sirene)
    debug_rules_parse_fog_toggle = function()
        assert(D.parse({ op = "fog", toggle = true }).toggle == true)
        assert(D.parse({ op = "fog", value = true }).toggle == false)
        assert(D.parse({ op = "fog", toggle = "sim" }) == nil)
    end,
    -- sprint 0055: params das almas no painel
    debug_rules_parse_alma_cfg = function()
        local a = D.parse({ op = "almaCfg", field = "popMin", value = 6 })
        assert(a and a.field == "popMin" and a.value == 6)
        a = D.parse({ op = "almaCfg", field = "crawler", value = 0.5 })
        assert(a and a.value == 0.5)
        a = D.parse({ op = "almaCfg", field = "white", value = false })
        assert(a and a.value == false)
        a = D.parse({ op = "almaCfg", field = "red" }) -- toggle (nil)
        assert(a and a.field == "red" and a.value == nil)
        assert(D.parse({ op = "almaCfg", field = "nope", value = 1 }) == nil)
        assert(D.parse({ op = "almaCfg", field = "popMin", value = "x" }) == nil)
        assert(D.parse({ op = "almaStatus" }).op == "almaStatus")
        assert(D.parse({ op = "almaReset" }).op == "almaReset")
    end,
}
